AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a RESTful API using API Gateway, Lambda and DynamoDB for the
  Wild Rydes serverless devops workshop
Parameters:
  ProjectId:
    Description: AWS CodeStar projectID used to associate new resources to team members
    Type: String
Resources:
  DeleteFunction:
    Properties:
      CodeUri: s3://aws-codestar-us-east-1-068896461592-uni-api-pipe/4efd07d5e74550939038786fbeb27578
      Description: Delete Unicorn
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        DELETE:
          Properties:
            Method: delete
            Path: /unicorns/{name}
          Type: Api
      FunctionName: uni-api-delete
      Handler: delete.lambda_handler
      Role:
        Fn::ImportValue:
          Fn::Join:
          - '-'
          - - Ref: ProjectId
            - Ref: AWS::Region
            - LambdaTrustRole
      Runtime: nodejs6.10
      Timeout: 10
      Tracing: Active
    Type: AWS::Serverless::Function
  ListFunction:
    Properties:
      CodeUri: s3://aws-codestar-us-east-1-068896461592-uni-api-pipe/4efd07d5e74550939038786fbeb27578
      Description: List Unicorns
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        GET:
          Properties:
            Method: get
            Path: /unicorns
          Type: Api
      FunctionName: uni-api-list
      Handler: list.lambda_handler
      Role:
        Fn::ImportValue:
          Fn::Join:
          - '-'
          - - Ref: ProjectId
            - Ref: AWS::Region
            - LambdaTrustRole
      Runtime: nodejs6.10
      Timeout: 10
      Tracing: Active
    Type: AWS::Serverless::Function
  ReadFunction:
    Properties:
      CodeUri: s3://aws-codestar-us-east-1-068896461592-uni-api-pipe/4efd07d5e74550939038786fbeb27578
      Description: View Unicorn by name
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        GET:
          Properties:
            Method: get
            Path: /unicorns/{name}
          Type: Api
      FunctionName: uni-api-read
      Handler: read.lambda_handler
      Role:
        Fn::ImportValue:
          Fn::Join:
          - '-'
          - - Ref: ProjectId
            - Ref: AWS::Region
            - LambdaTrustRole
      Runtime: nodejs6.10
      Timeout: 10
      Tracing: Active
    Type: AWS::Serverless::Function
  Table:
    Properties:
      PrimaryKey:
        Name: name
        Type: String
    Type: AWS::Serverless::SimpleTable
  UpdateFunction:
    Properties:
      CodeUri: s3://aws-codestar-us-east-1-068896461592-uni-api-pipe/4efd07d5e74550939038786fbeb27578
      Description: Update Unicorn
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        PUT:
          Properties:
            Method: put
            Path: /unicorns/{name}
          Type: Api
      FunctionName: uni-api-update
      Handler: update.lambda_handler
      Role:
        Fn::ImportValue:
          Fn::Join:
          - '-'
          - - Ref: ProjectId
            - Ref: AWS::Region
            - LambdaTrustRole
      Runtime: nodejs6.10
      Timeout: 10
      Tracing: Active
    Type: AWS::Serverless::Function
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar
