AWSTemplateFormatVersion: 2010-09-09
Description: Wild Rydes machine learning infrastructure
Resources:
  WildRydesMLGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Sub "wildrydesmlgluedatabase-${AWS::StackName}"
        Description: "Glue DB for Wild Rydes ML workshop"
      CatalogId: !Ref AWS::AccountId
  WildRydesMLGlueTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref WildRydesMLGlueDatabase
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: !Sub "externalweatherdatacsvtable-${AWS::StackName}"
        Parameters: { "classification" : "csv" }
        TableType: "EXTERNAL_TABLE"
        StorageDescriptor:
          Location:
            Fn::Sub: "s3://noaa-ghcn-pds/csv/"
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters: { "separatorChar" : ",", "field.delim": "," }
            SerializationLibrary: "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
          StoredAsSubDirectories: false
          Columns:
            - Name: id
              Type: string
            - Name: year_date
              Type: string
            - Name: element
              Type: string
            - Name: data_value
              Type: string
            - Name: m_flag
              Type: string
            - Name: q_flag
              Type: string
            - Name: s_flag
              Type: string
            - Name: obs_time
              Type: string
Outputs:
  AthenaSelectQuery:
    Value: !Sub |
      SELECT * FROM "${WildRydesMLGlueDatabase}"."${WildRydesMLGlueTable}" WHERE q_flag = '' AND id IN ('US1NYNY0074', 'USC00305798', 'USC00305799', 'USC00305804', 'USC00305806', 'USC00305816', 'USW00014732', 'USW00014786', 'USW00093732', 'USW00094728', 'USW00094789');
  AthenaCSVLocation:
    Value: !Sub |
      https://s3.console.aws.amazon.com/s3/buckets/aws-athena-query-results-${AWS::AccountId}-${AWS::Region}/Unsaved/?region=${AWS::Region}&tab=overview
