AWSTemplateFormatVersion: 2010-09-09
Description: Wild Rydes machine learning infrastructure
Parameters:
  RawBucketName:
    Description: Name of the S3 bucket with raw data
    Type: String
Resources:
  WildRydesMLGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Sub "wildrydesmlgluedatabase-${AWS::StackName}"
        Description: "Glue DB for Wild Rydes ML workshop"
      CatalogId: !Ref AWS::AccountId

  WildRydesMLGlueTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref WildRydesMLGlueDatabase
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: !Sub "externalweatherdatacsvtable-${AWS::StackName}"
        Parameters: { "classification" : "csv" }
        TableType: "EXTERNAL_TABLE"
        StorageDescriptor:
          Location:
            Fn::Sub: "s3://noaa-ghcn-pds/csv/"
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters: { "separatorChar" : ",", "field.delim": "," }
            SerializationLibrary: "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
          StoredAsSubDirectories: false
          Columns:
            - Name: id
              Type: string
            - Name: year_date
              Type: string
            - Name: element
              Type: string
            - Name: data_value
              Type: string
            - Name: m_flag
              Type: string
            - Name: q_flag
              Type: string
            - Name: s_flag
              Type: string
            - Name: obs_time
              Type: string
  DataProcessingExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        -
          PolicyName: "AllowTransformedBucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !Sub "arn:aws:s3:::${TransformedDataBucket}"
        -
          PolicyName: "AllowTransformedBucketObjects"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !Sub "arn:aws:s3:::${TransformedDataBucket}/*"
        -
          PolicyName: "AllowRawBucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !Sub "arn:aws:s3:::${RawBucketName}"
        -
          PolicyName: "AllowRawBucketObjects"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !Sub "arn:aws:s3:::${RawBucketName}/*"
        -
          PolicyName: "AllowNearestStationQueue"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !GetAtt NearestWeatherStationQueue.Arn
        -
          PolicyName: "AllowProcessedBucketQueue"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !GetAtt ProcessedUnicornDataQueue.Arn
        - PolicyName: "AllowLogging"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ['logs:*']
                Resource: 'arn:aws:logs:*:*:*'
  NearestWeatherStationQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      DelaySeconds: "0"
      MaximumMessageSize: "262144"
      MessageRetentionPeriod: "345600"
      ReceiveMessageWaitTimeSeconds: "0"
      VisibilityTimeout: "30"
  ProcessedUnicornDataQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      DelaySeconds: "0"
      MaximumMessageSize: "262144"
      MessageRetentionPeriod: "345600"
      ReceiveMessageWaitTimeSeconds: "0"
      VisibilityTimeout: "30"
  ProcessedDataToS3Function:
    Type: AWS::Lambda::Function
    Properties:
      Description: Wild Rydes lambda function to parse unicorn csv data and send downstream to lookup nearest groundstation
      Handler: index.handler
      MemorySize: 128
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref TransformedDataBucket
      Role: !GetAtt DataProcessingExecutionRole.Arn
      Runtime: python3.7
      Timeout: 3
      Tags:
        -
          Key: Workshop
          Value: Wild Rydes
        -
          Key: Module
          Value: Machine Learning
      Code:
        ZipFile: |
          import boto3
          import json
          import os
          
          client = boto3.client('s3')
          bucket = os.environ['OUTPUT_BUCKET']
          
          def handler(event, context):
              print('## EVENT')
              print(event)
              for record in event['Records']:
                  json_event = json.loads(record['body'])
                  key = get_key_from_event_json(json_event)
                  body = get_body_from_event_json(json_event)
                  upload_file(body, key)
              return event
          
          def get_key_from_event_json(event):
              time = event["statustime"].split(' ')[1]
              date = event["statustime"].split(' ')[0]
              return 'processed/' + date + '/' + event["name"] + '-' + time + '.json'
          
          def get_body_from_event_json(event):
              return json.dumps(event).encode()
          
          def upload_file(body, key):
              client.put_object(Body=body, Bucket=bucket, Key=key)

  ParseUnicornDataFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "central-multicustomer-aws-immersion-days"
        S3Key: "functions/wild-rydes-ml-lab/function.zip" 
      Description: Wild Rydes lambda function to parse unicorn csv data and send downstream to lookup nearest groundstation
      Handler: index.handler
      MemorySize: 128
      Environment:
        Variables:
          OUTPUT_QUEUE: !Ref NearestWeatherStationQueue
      Role: !GetAtt DataProcessingExecutionRole.Arn
      Runtime: nodejs10.x
      Timeout: 3
      Tags:
        -
          Key: Workshop
          Value: Wild Rydes
        -
          Key: Module
          Value: Machine Learning
  FindClosestGroundstationLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          from math import cos, asin, sqrt
          import boto3
          import json
          import os

          sqs = boto3.client('sqs')
          queue_url = os.environ['OUTPUT_QUEUE']

          def handler(event, context):
              print('## EVENT')
              print(event)
              for record in event['Records']:
                  json_event = json.loads(record['body'])
                  json_event = event_format_check(json_event)
                  json_event["groundstation"] = closest(groundstations(),
                                                      {"latitude": json_event["latitude"], "longitude": json_event["longitude" ]})["id"]
                  send_message_sqs(json_event)
              return event

          def send_message_sqs(event):
              response = sqs.send_message(
                  QueueUrl=queue_url,
                  DelaySeconds=0,
                  MessageBody=json.dumps(event)
              )
              print(response['MessageId'])

          def event_format_check(event):
              event["latitude"] = float(event["latitude"])
              event["longitude"] = float(event["longitude"])
              return event

          def distance(lat1, lon1, lat2, lon2):
              p = 0.017453292519943295
              a = 0.5 - cos((lat2-lat1)*p)/2 + cos(lat1*p)*cos(lat2*p) * (1-cos((lon2-lon1)*p)) / 2
              return 12742 * asin(sqrt(a))

          def closest(listOfStations, target):
              return min(listOfStations,
                          key=lambda p: distance(target['latitude'],target['longitude'],p['latitude'],p['longitude']))

          def groundstations():
              return [{"id": "US1NYNY0074",  "latitude": 40.7969, "longitude": -73.9330, "elevation": 6.1},
                      {"id": "USC00305798",  "latitude": 40.6000, "longitude": -73.9667, "elevation": 6.1},
                      {"id": "USC00305799",  "latitude": 40.8667, "longitude": -73.8833, "elevation": 27.1},
                      {"id": "USC00305804",  "latitude": 40.7333, "longitude": -73.9333, "elevation": 3.0},
                      {"id": "USC00305806",  "latitude": 40.8500, "longitude": -73.9167, "elevation": 54.9},
                      {"id": "USC00305816",  "latitude": 40.7000, "longitude": -74.0167, "elevation": 3.0},
                      {"id": "USW00014732",  "latitude": 40.7794, "longitude": -73.8803, "elevation": 3.4},
                      {"id": "USW00014786",  "latitude": 40.5833, "longitude": -73.8833, "elevation": 4.9},
                      {"id": "USW00093732",  "latitude": 39.8000, "longitude": -72.6667, "elevation": 25.9},
                      {"id": "USW00094728",  "latitude": 40.7789, "longitude": -73.9692, "elevation": 39.6},
                      {"id": "USW00094789",  "latitude": 40.6386, "longitude": -73.7622, "elevation": 3.4}]
      Description: Wild Rydes lambda function to look up nearest weather groundstation based on lat/long
      Handler: index.handler
      MemorySize: 128
      Environment:
        Variables:
          OUTPUT_QUEUE: !Ref ProcessedUnicornDataQueue
      Role: !GetAtt DataProcessingExecutionRole.Arn
      Runtime: python3.7
      Timeout: 3
      Tags:
        -
          Key: Workshop
          Value: Wild Rydes
        -
          Key: Module
          Value: Machine Learning
  
  LookUpNearestGroundstationEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties: 
      BatchSize: 10
      Enabled: True
      EventSourceArn: !GetAtt NearestWeatherStationQueue.Arn
      FunctionName: !Ref FindClosestGroundstationLambdaFunction
  
  ProcessedDataEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties: 
      BatchSize: 10
      Enabled: True
      EventSourceArn: !GetAtt ProcessedUnicornDataQueue.Arn
      FunctionName: !Ref ProcessedDataToS3Function
  
  TransformedDataBucket:
    Type: AWS::S3::Bucket
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      MaxSessionDuration: 3600
  SageMakerNotebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t3.medium
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      DirectInternetAccess: Enabled
      # DefaultCodeRepository:
      #   -
      VolumeSizeInGB: 5
      RootAccess: Enabled
  ModelBucket:
    Type: AWS::S3::Bucket
  InferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          print('inference function')
      Description: Wild Rydes inference function
      Handler: process.handler
      MemorySize: 128
      Role: !GetAtt DataProcessingExecutionRole.Arn
      Runtime: python3.7
      Timeout: 3
      Tags:
        -
          Key: Workshop
          Value: Wild Rydes
        -
          Key: Module
          Value: Machine Learning
  #API Gateway
Outputs:
  AthenaSelectQuery:
    Value: !Sub |
      SELECT *
      FROM "${WildRydesMLGlueDatabase}"."${WildRydesMLGlueTable}"
      WHERE q_flag = ''
              AND id IN ('US1NYNY0074', 'USC00305798', 'USC00305799', 'USC00305804', 'USC00305806', 'USC00305816', 'USW00014732', 'USW00014786', 'USW00093732', 'USW00094728', 'USW00094789');
  AthenaCSVLocation:
    Value: !Sub |
      https://s3.console.aws.amazon.com/s3/buckets/aws-athena-query-results-${AWS::AccountId}-${AWS::Region}/Unsaved/?region=${AWS::Region}&tab=overview
  AthenaCreateTableQuery:
    Value: !Sub |
      CREATE TABLE "${WildRydesMLGlueDatabase}".nygroundstationdata
      WITH ( format='TEXTFILE', external_location='s3://${TransformedDataBucket}/nygroundstationdata/' ) AS
      SELECT *
      FROM "${WildRydesMLGlueDatabase}"."${WildRydesMLGlueTable}"
      WHERE q_flag = ''
              AND id IN ('US1NYNY0074', 'USC00305798', 'USC00305799', 'USC00305804', 'USC00305806', 'USC00305816', 'USW00014732', 'USW00014786', 'USW00093732', 'USW00094728', 'USW00094789');
  TransformedDataBucketName:
    Value: !Ref TransformedDataBucket
  ModelBucketName:
    Value: !Ref ModelBucket
